version: '3.1'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress_test
      MYSQL_USER: example        # Set user for MySQL
      MYSQL_PASSWORD: example    # Set password for MySQL user
    volumes:
      - mysql_data:/var/lib/mysql # Persist MySQL data

  wordpress:
    image: wordpress:php7.1
    restart: always
    ports:
      - 8888:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: wordpress_test
      WORDPRESS_DB_USER: example
      WORDPRESS_DB_PASSWORD: example
      ABSPATH: /usr/src/wordpress/
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define( 'SCRIPT_DEBUG', true );
    volumes:
      - wordpress_data:/var/www/html
      - .:/var/www/html/wp-content/plugins/live-composer-page-builder
    depends_on:
      - mysql

  cli:
    image: wordpress:cli
    restart: always
    user: www-data # Use the default www-data user for WordPress container
    volumes:
      - wordpress_data:/var/www/html
      - .:/var/www/html/wp-content/plugins/live-composer-page-builder
    depends_on:
      - mysql
      - wordpress

  wordpress_phpunit:
    image: chriszarate/wordpress-phpunit
    restart: always
    environment:
      PHPUNIT_DB_HOST: mysql
    volumes:
      - .:/app
      - testsuite:/tmp
    depends_on:
      - mysql

  composer:
    image: composer
    restart: always
    volumes:
      - .:/app

  wordpress_e2e_tests:
    image: wordpress
    restart: always
    ports:
      - 8889:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: wordpress_e2e_tests
      WORDPRESS_DB_USER: example
      WORDPRESS_DB_PASSWORD: example
      ABSPATH: /usr/src/wordpress/
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define( 'SCRIPT_DEBUG', true );
    volumes:
      - wordpress_e2e_tests_data:/var/www/html
      - .:/var/www/html/wp-content/plugins/live-composer-page-builder
    depends_on:
      - mysql

  cli_e2e_tests:
    image: wordpress:cli
    restart: always
    user: www-data
    volumes:
      - wordpress_e2e_tests_data:/var/www/html
      - .:/var/www/html/wp-content/plugins/live-composer-page-builder
    depends_on:
      - mysql
      - wordpress_e2e_tests

volumes:
  testsuite:
  wordpress_data:
  wordpress_e2e_tests_data:
  mysql_data: # Persistent volume for MySQL
